import { Topic, RumorPost, UserPersona, TopicRoom, CatalogScreenItem } from '../types';

export const INITIAL_TOPICS: Topic[] = [
  {
    id: 'topic-1',
    title: 'AI Layoffs vs Reality',
    category: 'Tech',
    debaterCount: 1420,
    heatScore: 98,
    matchRate: 94,
    isHot: true,
    isSubscribed: true,
    description: 'Are headcount cuts truly driven by AI productivity gains, or executive margin preservation?'
  },
  {
    id: 'topic-2',
    title: 'Office Politics & Ghost Promos',
    category: 'Workplace',
    debaterCount: 890,
    heatScore: 91,
    matchRate: 88,
    isHot: true,
    isSubscribed: true,
    description: 'Promised promotions postponed indefinitely while responsibilities multiply.'
  },
  {
    id: 'topic-3',
    title: 'Startup Chaos & Seed Valuations',
    category: 'Startups',
    debaterCount: 760,
    heatScore: 86,
    matchRate: 82,
    isHot: false,
    isSubscribed: false,
    description: 'Burn rates spiraling as AI wrapper startups face platform commoditization.'
  },
  {
    id: 'topic-4',
    title: 'The Death of Organic Dating in 2026',
    category: 'Social',
    debaterCount: 1240,
    heatScore: 95,
    matchRate: 91,
    isHot: true,
    isSubscribed: false,
    description: 'Curated profiles killed genuine spark. Why anonymous topic friction builds real bonds.'
  },
  {
    id: 'topic-5',
    title: 'Stealth Whistleblowing Culture',
    category: 'Spicy',
    debaterCount: 630,
    heatScore: 89,
    matchRate: 85,
    isHot: false,
    isSubscribed: true,
    description: 'How encrypted topic channels are replacing HR mediation across Tier-1 tech.'
  },
  {
    id: 'topic-6',
    title: 'Remote Work Surveillance Backlash',
    category: 'Workplace',
    debaterCount: 950,
    heatScore: 93,
    matchRate: 89,
    isHot: true,
    isSubscribed: false,
    description: 'Keystroke logging and biometric presence trackers triggering mass silent boycotts.'
  }
];

export const INITIAL_RUMORS: RumorPost[] = [
  {
    id: 'rumor-1',
    topicId: 'topic-1',
    topicTitle: 'AI Layoffs vs Reality',
    category: 'Tech',
    authorHandle: 'void_whisperer',
    authorChaosIndex: 87,
    content: 'A tier-1 cloud provider quietly mandated all managers replace 20% of contractor headcount with LLM agents before Q4 review.',
    encryptedContent: 'A tier-1 cloud provider quietly mandated [REDACTED] to replace 20% of [ENCRYPTED_DEPARTMENT] with LLM orchestration by [DATE_LOCKED].',
    isEncrypted: true,
    matchRate: 94,
    agrees: 342,
    debates: 89,
    timestamp: '12m ago',
    tags: ['#CLOUD_WARS', '#AGENT_REPLACEMENT', '#LEAK']
  },
  {
    id: 'rumor-2',
    topicId: 'topic-2',
    topicTitle: 'Office Politics & Ghost Promos',
    category: 'Workplace',
    authorHandle: 'stealth_director',
    authorChaosIndex: 92,
    content: 'Leadership just froze all L6 promotions for the third quarter in a row, yet approved 4 external VP hires in the same week.',
    encryptedContent: 'Leadership just froze all [LEVEL_LOCKED] promos while [REDACTED_VP_COUNT] external hires were cleared in secret.',
    isEncrypted: false,
    matchRate: 88,
    agrees: 512,
    debates: 144,
    timestamp: '34m ago',
    tags: ['#GHOST_PROMOS', '#INTERNAL_MOBILITY', '#UNFILTERED']
  },
  {
    id: 'rumor-3',
    topicId: 'topic-4',
    topicTitle: 'The Death of Organic Dating in 2026',
    category: 'Social',
    authorHandle: 'neon_stoic',
    authorChaosIndex: 78,
    content: 'Matching on shared intellectual conflict has a 4.2x higher chat retention rate than photo-first swipe apps.',
    encryptedContent: 'Matching on [FRICTION_INDEX] yields 4.2x higher [RETENTION_METRIC] than swipe mechanics.',
    isEncrypted: true,
    matchRate: 91,
    agrees: 289,
    debates: 67,
    timestamp: '1h ago',
    tags: ['#TOPIC_FIRST', '#FRICTION_MATCH', '#DATA']
  },
  {
    id: 'rumor-4',
    topicId: 'topic-3',
    topicTitle: 'Startup Chaos & Seed Valuations',
    category: 'Startups',
    authorHandle: 'cap_table_rogue',
    authorChaosIndex: 95,
    content: 'Three YC W26 startups in our co-working hub just pivoted from autonomous agents back to vertical SaaS with human-in-the-loop.',
    encryptedContent: 'Three [BATCH_LOCKED] companies in [CITY_ENCRYPTED] pivoted away from full autonomy due to margin decay.',
    isEncrypted: false,
    matchRate: 82,
    agrees: 420,
    debates: 115,
    timestamp: '2h ago',
    tags: ['#STARTUP_PIVOT', '#UNIT_ECONOMICS', '#FOUNDERS']
  }
];

export const MOCK_MATCH_PARTNER: UserPersona = {
  id: 'partner-99',
  handle: 'cipher_vanguard',
  tagline: 'Contrarian systems architect • AI safety cynic',
  city: 'San Francisco, CA',
  role: 'Staff ML Infrastructure Engineer',
  realName: 'Elena Rostova',
  chaosIndex: 91,
  avatarSeed: 'cipher',
  realPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80',
  affinities: [
    { topic: 'AI Layoffs vs Reality', score: 96 },
    { topic: 'Office Politics', score: 89 },
    { topic: 'Stealth Whistleblowing', score: 92 },
    { topic: 'Modern Dating Friction', score: 84 }
  ]
};

export const MOCK_ROOMS: TopicRoom[] = [
  {
    id: 'room-1',
    title: 'Startup Chaos // The 2026 Burn Rate Reckoning',
    category: 'Startups',
    activeSpeakers: 4,
    listeners: 182,
    isLive: true,
    hostHandle: 'seed_survivor',
    recentDebate: 'VCs are demanding 80% gross margins on agentic architectures.'
  },
  {
    id: 'room-2',
    title: 'Office Politics // Survived a Corporate Reorg AMA',
    category: 'Workplace',
    activeSpeakers: 3,
    listeners: 94,
    isLive: true,
    hostHandle: 'masked_em',
    recentDebate: 'How to position your team before the Q3 consolidation.'
  },
  {
    id: 'room-3',
    title: 'AI vs Human Coders // Junior Engineering Extinction?',
    category: 'Tech',
    activeSpeakers: 6,
    listeners: 310,
    isLive: true,
    hostHandle: 'kernel_panic',
    recentDebate: 'Is prompt architecture actually replacing junior dev pipelines?'
  }
];

export const ALL_66_SCREENS: CatalogScreenItem[] = [
  { index: 1, id: '01', title: 'Shader Effect', category: 'Shader', viewTarget: 'feed', htmlFile: 'screens/01_shader.html', width: '390', height: '884' },
  { index: 2, id: '02', title: 'AI Moderation Nudge', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/02_ai_moderation_nudge.html', screenshotFile: 'screenshots/02_ai_moderation_nudge.png', width: '780', height: '2764' },
  { index: 3, id: '03', title: 'Premium Topic Boost Analytics', category: 'Boost', viewTarget: 'boost', htmlFile: 'screens/03_premium_topic_boost_analytics.html', screenshotFile: 'screenshots/03_premium_topic_boost_analytics.png', width: '780', height: '1768' },
  { index: 4, id: '04', title: 'Topic Selection Matrix', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/04_topic_selection.html', screenshotFile: 'screenshots/04_topic_selection.png', width: '780', height: '1952' },
  { index: 5, id: '05', title: 'Shader Canvas 2', category: 'Shader', viewTarget: 'feed', htmlFile: 'screens/05_shader.html', width: '390', height: '884' },
  { index: 6, id: '06', title: 'Discovery Feed Core', category: 'Feed', viewTarget: 'feed', htmlFile: 'screens/06_discovery_feed.html', screenshotFile: 'screenshots/06_discovery_feed.png', width: '780', height: '1768' },
  { index: 7, id: '07', title: 'Edit Topics & Filters', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/07_edit_topics.html', screenshotFile: 'screenshots/07_edit_topics.png', width: '780', height: '1768' },
  { index: 8, id: '08', title: 'AI Topic Validation Queue', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/08_ai_topic_validation_queue_high-fidelity_fix.html', screenshotFile: 'screenshots/08_ai_topic_validation_queue_high-fidelity_fix.png', width: '780', height: '2640' },
  { index: 9, id: '09', title: 'AI Matchmaker Engine', category: 'Matching', viewTarget: 'matchmaker', htmlFile: 'screens/09_ai_matchmaker.html', screenshotFile: 'screenshots/09_ai_matchmaker.png', width: '780', height: '1768' },
  { index: 10, id: '10', title: 'Discovery Preferences', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/10_discovery_preferences.html', screenshotFile: 'screenshots/10_discovery_preferences.png', width: '780', height: '1768' },
  { index: 11, id: '11', title: 'Topic Detail: Office Politics', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/11_topic_detail_office_politics.html', screenshotFile: 'screenshots/11_topic_detail_office_politics.png', width: '780', height: '3200' },
  { index: 12, id: '12', title: 'AI Moderation Immersive', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/12_ai_moderation_immersive_validation.html', screenshotFile: 'screenshots/12_ai_moderation_immersive_validation.png', width: '780', height: '2400' },
  { index: 13, id: '13', title: 'Discovery Main Hub', category: 'Feed', viewTarget: 'feed', htmlFile: 'screens/13_discovery_main_hub.html', screenshotFile: 'screenshots/13_discovery_main_hub.png', width: '780', height: '2800' },
  { index: 14, id: '14', title: 'Boost Your Topic CTA', category: 'Boost', viewTarget: 'boost', htmlFile: 'screens/14_boost_your_topic.html', screenshotFile: 'screenshots/14_boost_your_topic.png', width: '780', height: '1768' },
  { index: 15, id: '15', title: 'Active Chat Session', category: 'Chat', viewTarget: 'chat', htmlFile: 'screens/15_active_chat.html', screenshotFile: 'screenshots/15_active_chat.png', width: '780', height: '1768' },
  { index: 16, id: '16', title: 'Rumr Premium Pro', category: 'Boost', viewTarget: 'boost', htmlFile: 'screens/16_rumr_premium_pro.html', screenshotFile: 'screenshots/16_rumr_premium_pro.png', width: '780', height: '2200' },
  { index: 17, id: '17', title: 'Topics Exploration Radar', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/17_topics_exploration.html', screenshotFile: 'screenshots/17_topics_exploration.png', width: '780', height: '2400' },
  { index: 18, id: '18', title: 'AI Moderation Nudge (User)', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/18_ai_moderation_nudge_user.html', screenshotFile: 'screenshots/18_ai_moderation_nudge_user.png', width: '780', height: '1768' },
  { index: 19, id: '19', title: 'Active Chat Stream', category: 'Chat', viewTarget: 'chat', htmlFile: 'screens/19_active_chat.html', screenshotFile: 'screenshots/19_active_chat.png', width: '780', height: '1768' },
  { index: 20, id: '20', title: 'Topic Graph Visualization', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/20_topic_graph_visualization.html', screenshotFile: 'screenshots/20_topic_graph_visualization.png', width: '780', height: '1768' },
  { index: 21, id: '21', title: 'Safety & Reporting Center', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/21_safety_reporting.html', screenshotFile: 'screenshots/21_safety_reporting.png', width: '780', height: '2788' },
  { index: 22, id: '22', title: 'Global Settings & Privacy', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/22_global_settings_privacy_history.html', screenshotFile: 'screenshots/22_global_settings_privacy_history.png', width: '780', height: '2000' },
  { index: 23, id: '23', title: 'Thread Detail: Ghosting', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/23_thread_detail_ghosting_discussion.html', screenshotFile: 'screenshots/23_thread_detail_ghosting_discussion.png', width: '780', height: '2900' },
  { index: 24, id: '24', title: 'Enter Verification Code (OTP)', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/24_enter_verification_code.html', screenshotFile: 'screenshots/24_enter_verification_code.png', width: '780', height: '1768' },
  { index: 25, id: '25', title: 'Safety: Report User Incident', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/25_safety_report_user.html', screenshotFile: 'screenshots/25_safety_report_user.png', width: '780', height: '1768' },
  { index: 26, id: '26', title: 'Premium Checkout Flow', category: 'Boost', viewTarget: 'boost', htmlFile: 'screens/26_premium_checkout_topic_boost.html', screenshotFile: 'screenshots/26_premium_checkout_topic_boost.png', width: '780', height: '2200' },
  { index: 27, id: '27', title: 'Shader 3', category: 'Shader', viewTarget: 'feed', htmlFile: 'screens/27_shader.html', width: '390', height: '884' },
  { index: 28, id: '28', title: 'Splash Screen 1', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/28_splash_screen.html', screenshotFile: 'screenshots/28_splash_screen.png', width: '780', height: '1768' },
  { index: 29, id: '29', title: 'Splash Screen 2', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/29_splash_screen.html', screenshotFile: 'screenshots/29_splash_screen.png', width: '780', height: '1768' },
  { index: 30, id: '30', title: 'Welcome & Philosophy Onboarding', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/30_welcome_onboarding.html', screenshotFile: 'screenshots/30_welcome_onboarding.png', width: '780', height: '1768' },
  { index: 31, id: '31', title: 'App Settings Hub', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/31_app_settings.html', screenshotFile: 'screenshots/31_app_settings.png', width: '780', height: '1768' },
  { index: 32, id: '32', title: 'Global System Health Overview', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/32_global_system_health_overview.html', screenshotFile: 'screenshots/32_global_system_health_overview.png', width: '780', height: '2600' },
  { index: 33, id: '33', title: 'Discovery Feed Spicy Mode', category: 'Feed', viewTarget: 'feed', htmlFile: 'screens/33_discovery_feed.html', screenshotFile: 'screenshots/33_discovery_feed.png', width: '780', height: '1768' },
  { index: 34, id: '34', title: 'Chaos Normalization Logs', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/34_chaos_normalization_logs.html', screenshotFile: 'screenshots/34_chaos_normalization_logs.png', width: '780', height: '2400' },
  { index: 35, id: '35', title: 'AI Distance Score Visualizer', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/35_refined_ai_distance_score_visualization.html', screenshotFile: 'screenshots/35_refined_ai_distance_score_visualization.png', width: '780', height: '2500' },
  { index: 36, id: '36', title: 'Flagged Content Detail', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/36_flagged_content_detail_high-fidelity_refinement.html', screenshotFile: 'screenshots/36_flagged_content_detail_high-fidelity_refinement.png', width: '780', height: '2200' },
  { index: 37, id: '37', title: 'Profile Reveal Moment', category: 'Chat', viewTarget: 'chat', htmlFile: 'screens/37_profile_reveal_moment.html', screenshotFile: 'screenshots/37_profile_reveal_moment.png', width: '1266', height: '3054' },
  { index: 38, id: '38', title: 'Landing Page Hero', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/38_landing_page.html', screenshotFile: 'screenshots/38_landing_page.png', width: '780', height: '3476' },
  { index: 39, id: '39', title: 'Shader 4', category: 'Shader', viewTarget: 'feed', htmlFile: 'screens/39_shader.html', width: '390', height: '884' },
  { index: 40, id: '40', title: 'Global Search Modal', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/40_global_search.html', screenshotFile: 'screenshots/40_global_search.png', width: '780', height: '1768' },
  { index: 41, id: '41', title: 'Topic Rooms Discovery Hub', category: 'Rooms', viewTarget: 'rooms', htmlFile: 'screens/41_topic_rooms_discovery.html', screenshotFile: 'screenshots/41_topic_rooms_discovery.png', width: '780', height: '3604' },
  { index: 42, id: '42', title: 'Discovery Distance Filters', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/42_discovery_filters.html', screenshotFile: 'screenshots/42_discovery_filters.png', width: '780', height: '1768' },
  { index: 43, id: '43', title: 'Safety & Privacy Guarantee', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/43_safety_promise.html', screenshotFile: 'screenshots/43_safety_promise.png', width: '780', height: '1768' },
  { index: 44, id: '44', title: 'My Chaos Profile Main', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/44_my_chaos_profile.html', screenshotFile: 'screenshots/44_my_chaos_profile.png', width: '780', height: '2940' },
  { index: 45, id: '45', title: 'Splash Screen 3', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/45_splash_screen.html', screenshotFile: 'screenshots/45_splash_screen.png', width: '780', height: '1768' },
  { index: 46, id: '46', title: 'Match Reveal Card', category: 'Matching', viewTarget: 'matchmaker', htmlFile: 'screens/46_match_reveal.html', screenshotFile: 'screenshots/46_match_reveal.png', width: '780', height: '1768' },
  { index: 47, id: '47', title: 'Premium Boost Tier Modal', category: 'Boost', viewTarget: 'boost', htmlFile: 'screens/47_premium_checkout_topic_boost.html', screenshotFile: 'screenshots/47_premium_checkout_topic_boost.png', width: '780', height: '1768' },
  { index: 48, id: '48', title: 'Profile Basics & Persona Setup', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/48_profile_basics.html', screenshotFile: 'screenshots/48_profile_basics.png', width: '780', height: '2246' },
  { index: 49, id: '49', title: 'How It Works: Topic > Person', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/49_how_it_works_-_topics.html', screenshotFile: 'screenshots/49_how_it_works_-_topics.png', width: '780', height: '1768' },
  { index: 50, id: '50', title: 'User Reports Management', category: 'Safety', viewTarget: 'safety', htmlFile: 'screens/50_user_reports_management.html', screenshotFile: 'screenshots/50_user_reports_management.png', width: '780', height: '2200' },
  { index: 51, id: '51', title: 'Identity Reveal Animated', category: 'Chat', viewTarget: 'chat', htmlFile: 'screens/51_identity_reveal_animated_unmasking.html', screenshotFile: 'screenshots/51_identity_reveal_animated_unmasking.png', width: '780', height: '3200' },
  { index: 52, id: '52', title: 'Matches Feed Inbox', category: 'Matching', viewTarget: 'matchmaker', htmlFile: 'screens/52_matches_feed.html', screenshotFile: 'screenshots/52_matches_feed.png', width: '780', height: '1768' },
  { index: 53, id: '53', title: 'Topic-Based Navigation Flow', category: 'Flow', viewTarget: 'catalog', htmlFile: 'screens/53_rumr_topic-based_discovery_flow.html', width: '390', height: '884' },
  { index: 54, id: '54', title: 'Topic Graph Matrix 2', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/54_topic_graph_visualization.html', screenshotFile: 'screenshots/54_topic_graph_visualization.png', width: '780', height: '1768' },
  { index: 55, id: '55', title: 'Match Reveal Instant', category: 'Matching', viewTarget: 'matchmaker', htmlFile: 'screens/55_match_reveal.html', screenshotFile: 'screenshots/55_match_reveal.png', width: '780', height: '1768' },
  { index: 56, id: '56', title: 'Shader 5', category: 'Shader', viewTarget: 'feed', htmlFile: 'screens/56_shader.html', width: '390', height: '884' },
  { index: 57, id: '57', title: 'Topic Boost Pro (Premium)', category: 'Boost', viewTarget: 'boost', htmlFile: 'screens/57_topic_boost_premium.html', screenshotFile: 'screenshots/57_topic_boost_premium.png', width: '780', height: '1768' },
  { index: 58, id: '58', title: 'Phone Verification Screen', category: 'Onboarding', viewTarget: 'onboarding', htmlFile: 'screens/58_phone_verification.html', screenshotFile: 'screenshots/58_phone_verification.png', width: '780', height: '1768' },
  { index: 59, id: '59', title: 'My Topic Profile Metrics', category: 'Profile', viewTarget: 'profile', htmlFile: 'screens/59_my_topic_profile.html', screenshotFile: 'screenshots/59_my_topic_profile.png', width: '780', height: '2200' },
  { index: 60, id: '60', title: 'Create Custom Topic Node', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/60_create_custom_topic.html', screenshotFile: 'screenshots/60_create_custom_topic.png', width: '780', height: '1768' },
  { index: 61, id: '61', title: 'Profile Reveal Step 2', category: 'Chat', viewTarget: 'chat', htmlFile: 'screens/61_profile_reveal_moment.html', screenshotFile: 'screenshots/61_profile_reveal_moment.png', width: '780', height: '1768' },
  { index: 62, id: '62', title: 'Topic Room: Startup Chaos', category: 'Rooms', viewTarget: 'rooms', htmlFile: 'screens/62_topic_room_startup_chaos.html', screenshotFile: 'screenshots/62_topic_room_startup_chaos.png', width: '780', height: '2800' },
  { index: 63, id: '63', title: 'Topic Selector Grid', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/63_topic_selection.html', screenshotFile: 'screenshots/63_topic_selection.png', width: '780', height: '1768' },
  { index: 64, id: '64', title: 'Identity Reveal Permission', category: 'Chat', viewTarget: 'chat', htmlFile: 'screens/64_identity_reveal_permission.html', screenshotFile: 'screenshots/64_identity_reveal_permission.png', width: '780', height: '1768' },
  { index: 65, id: '65', title: 'Communities & Guilds Hub', category: 'Discovery', viewTarget: 'topics', htmlFile: 'screens/65_communities_hub.html', screenshotFile: 'screenshots/65_communities_hub.png', width: '780', height: '2600' },
  { index: 66, id: '66', title: 'Match Reveal High-Tension', category: 'Matching', viewTarget: 'matchmaker', htmlFile: 'screens/66_match_reveal_high-tension_unmasking.html', screenshotFile: 'screenshots/66_match_reveal_high-tension_unmasking.png', width: '780', height: '2400' }
];
